language: java
jdk:
- oraclejdk8
sudo: false
script:
 gradle executeFeatures -PapiToken=${apiToken}
branches:
  only: develop
notifications:
 email: true 
 recipients:
 - Rosario.Garcia@fundacion-jala.org