language: java
jdk:
- oraclejdk8
sudo: true
script:
 gradle executeFeatures -PapiToken="11ad529712e337a3661f599d2034be8e"
branches:
  only: develop
notifications:
 email: true 
 recipients:
 - Rosario.Garcia@fundacion-jala.org