language: java
jdk:
- oraclejdk8
sudo: true
env:
-$apiToken="11ad529712e337a3661f599d2034be8e"
script: executeFeatures -PapiToken=$apiToken
branches:
  only: develop
notifications:
 email: true 
 recipients:
 - Rosario.Garcia@fundacion-jala.org