language: java
jdk:
- oraclejdk8
sudo: required
env:
 - $apiToken= "b79614721c9f3fbc59017e10752c2a0b"
script: gradle executeFeatures -PapiToken=$apiToken
branches:
only:
   - develop
   - test
notifications:
 email: true 
 recipients:
 - Rosario.Garcia@fundacion-jala.org
 - Bruno.Barrios@fundacion-jala.org
