language: java
jdk:
- oraclejdk8
sudo: required

before_install:
openssl aes-256-cbc -K $encrypted_0a6446eb3ae3_key -iv $encrypted_0a6446eb3ae3_key -in gradle.properties.enc -out gradle.properties -d

branches:
only: develop

notifications:
 email: true 
 recipients:
 - Rosario.Garcia@fundacion-jala.org
 - Bruno.Barrios@fundacion-jala.org
