language: java
jdk:
- oraclejdk8
sudo: required

env:
 - secure: "HPQbvDeTZuicJ93qQ378MADdWXcp+Fbxffqb1sF6EJ09SWCuyc4FWBgwBwbrP4YHyzYieraMTNRalkxz4Hf4MQI6wNQN9qoZjiuLmvtkf8xY/P5oF2WtTZGAwfHwfKbHlvjYNlbS7iySQNKZgOhR3FXq46raLDbXOCA927c7QNX7LJfHDz1Sk+ukWtPXI+8Dql6kyGmA5s7oTri2FMpUtXaTG3kXsdRpyZyrCmH1127hSk644OzIYTlEgzy+Iu5Aoaaugfe4mfAfl3yoAkqaJWa0I6OxzwGut0ylysJVzx1Oj0wgcLEEkHiHJ+2Xa3AkRWO6DFYLJTgrJp2KySfRonco8vvyfSa8Kcd5iEdYTylOo7jzW/ym26uqAtO8XveOkaVq9Zs1eF3cWHOJMgU92KlO/M70TQxCY7eTbYLE6c7IxwtFx/0vHYRKBJV1UK5lns21wTHQN2pBx/5//GB8GHewfl5t+no+32b82Y4aXHyZOOwBxheiMBy+jbhcHdDVVKqiFN1vM8Vpl2e7qhxrTPgMDoufoVSU3iW1VmJIyZOZPSy+vLdmWesNjICzdzgSOlaTtsG878g+6uEPNo9EAmCvkDIRYRV9fiypxh/7a7h8ro3Pp2jdIP0A+uTBIfatdLzEqK9s6J03GB2vaLUwNR4R9IEb/lZUTA9KVujvG2o="
script: gradle executeFeatures -PapiToken=secure
branches:
only: develop

notifications:
 email: true 
 recipients:
 - Rosario.Garcia@fundacion-jala.org
 - Bruno.Barrios@fundacion-jala.org
