language: java
jdk:
- oraclejdk8
sudo: required
script: bundle exec rake build && bundle exec rake builddoc
branches:
  only: develop
notifications:
 email: true 
 recipients:
 - QADEV07@fundacion-jala.org