language: java
jdk:
- oraclejdk8
sudo: required
script: gradle executeFeatures -PapiToken=$apiToken
branches:
   - develop
   - test
notifications:
 email: true 
 recipients:
 - Rosario.Garcia@fundacion-jala.org
 - Bruno.Barrios@fundacion-jala.org
